import fs from "fs";
import path from "path";

import { SVIFile } from "./types";
import { LLMProcessor } from "../llm/llm";
import { SviConfig } from "../config/config";
import { extractDeclarationsPromptTemplate } from "./prompts/extractDeclarations";
import CacheManager from "./cacheManager";
import logger from "../utils/logger";
import { getRelativePath } from "../utils/file";

export default class SviDependencies {
  private llmProcessor: LLMProcessor;
  private config: SviConfig;
  private declarations: { relativePath: string; content: string }[] = [];
  private llmGeneratedFiles: string[] = [];
  private cachedFiles: string[] = [];

  constructor(llmProcessor: LLMProcessor, config: SviConfig) {
    this.llmProcessor = llmProcessor;
    this.config = config;
    logger.trace("SviDependencies constructor called.");
  }

  public async loadDependenciesDeclarations(sviFile: SVIFile): Promise<boolean> {
    logger.trace(`Starting loadDependenciesDeclarations for SVI file: ${sviFile.getSviFileName()}`);
    this.declarations = []; // Clear previous declarations
    this.llmGeneratedFiles = [];
    this.cachedFiles = [];

    const dependencies = sviFile.dependencies || [];
    if (dependencies.length === 0) {
      logger.debug(`No dependencies found for ${sviFile.getSviFileName()}.`);
      return true;
    }

    const sviFileDirectory = sviFile.getSviFileDirectory();

    for (const dependencyFilename of dependencies) {
      logger.debug(`Processing dependency: ${dependencyFilename}`);
      let dependencyFullPath: string;

      // Resolve dependency path: If dependencyFilename is absolute, path.resolve returns it as is.
      // Otherwise, it resolves relative to sviFileDirectory.
      dependencyFullPath = path.resolve(sviFileDirectory, dependencyFilename);

      if (!fs.existsSync(dependencyFullPath)) {
        logger.error(`File '${dependencyFilename}' from 'Dependencies' section not found in the path '${dependencyFullPath}'.`);
        return false;
      }

      logger.trace(`Dependency '${dependencyFilename}' resolved to full path: '${dependencyFullPath}'`);

      const dependencyFileDirectory = path.dirname(dependencyFullPath);
      const cacheManager = new CacheManager(dependencyFileDirectory);
      let dependencyDeclarations: string | null = null;
      const relativeDependencyPath = getRelativePath(dependencyFullPath, this.config.configDir);

      // Check cache
      if (cacheManager.isFileExportsCacheValid(dependencyFilename)) {
        dependencyDeclarations = cacheManager.getFileExportsFromCache(dependencyFilename);
        if (dependencyDeclarations !== null) { // Check for null explicitly, empty string is valid
          this.declarations.push({ relativePath: relativeDependencyPath, content: dependencyDeclarations });
          this.cachedFiles.push(relativeDependencyPath);
          logger.trace(`Declarations for '${relativeDependencyPath}' loaded from cache.`);
          continue; // Go to next dependency
        } else {
          logger.warning(`Cache for '${relativeDependencyPath}' was valid but returned empty content. Regenerating with LLM.`);
        }
      }

      // Generate declarations by LLM
      logger.info(`LLM will be called to generate declarations for file: '${relativeDependencyPath}'`);
      this.llmGeneratedFiles.push(relativeDependencyPath);

      let sourceCode: string;
      try {
        sourceCode = fs.readFileSync(dependencyFullPath, 'utf8');
      } catch (error) {
        logger.error(`Failed to read dependency file '${dependencyFullPath}': ${error}`);
        return false;
      }

      const programmingLanguagePhrase = this.config.programmingLanguage ? `programming language ${this.config.programmingLanguage}` : '';

      const prompt = extractDeclarationsPromptTemplate
        .replace('{{programmingLanguage}}', programmingLanguagePhrase)
        .replace('{{sourceCode}}', sourceCode);

      dependencyDeclarations = await this.llmProcessor.ask(prompt);

      if (!dependencyDeclarations || dependencyDeclarations.trim() === '') {
        logger.error(`LLM returned no declarations for file: '${relativeDependencyPath}'.`);
        return false;
      }

      // Update cache
      cacheManager.updateFileExportsInCache(dependencyFilename, dependencyDeclarations);
      logger.trace(`Declarations for '${relativeDependencyPath}' generated by LLM and updated in cache.`);

      this.declarations.push({ relativePath: relativeDependencyPath, content: dependencyDeclarations });
    }

    // Log final summary
    let summaryMessage = "Dependencies declarations were retrieved and added to the main prompt.";
    if (this.llmGeneratedFiles.length > 0) {
      summaryMessage += "\n  Generated by LLM:\n    - " + this.llmGeneratedFiles.join("\n    - ");
    }
    if (this.cachedFiles.length > 0) {
      summaryMessage += "\n  Taken from cache:\n    - " + this.cachedFiles.join("\n    - ");
    }
    logger.info(summaryMessage);

    return true;
  }

  public getDependenciesDeclarationsAsString(): string {
    logger.trace("Generating dependencies declarations as string.");
    if (this.declarations.length === 0) {
      return "";
    }

    let resultParts: string[] = [];
    for (const decl of this.declarations) {
      let block = `Declarations from file: ${decl.relativePath}\n`; // Line 1
      block += "\n"; // Empty line (Line 2)
      block += decl.content; // The declarations (Line 3 onwards, potentially multiline)
      if (!block.endsWith('\n')) {
          block += '\n'; // Ensure content ends with a newline to separate from the next empty line
      }
      resultParts.push(block);
    }
    // Join parts with an additional empty line between them, as per "empty line \n Next declaration (if any)"
    // Each block already ends with a newline. Joining with "\n" adds the required empty line.
    return resultParts.join("\n");
  }
}