import fs from "fs";
import path from "path";
import { SVIFile } from "./types";
import { LLMProcessor } from "../llm/llm";
import { SviConfig } from "../config/config";
import { extractDeclarationsPromptTemplate } from "./prompts/extractDeclarations";
import CacheManager from "./cacheManager";
import logger from "../utils/logger";

interface DependencyDeclaration {
  originalDependencyName: string; // The name as it appears in sviFile.dependencies
  fullPath: string; // The resolved full path to the file
  content: string; // The declarations content
}

export default class SviDependencies {
  private llmProcessor: LLMProcessor;
  private config: SviConfig;
  private _declarations: DependencyDeclaration[] = [];
  private _llmGeneratedFiles = new Set<string>(); // Stores full paths of files whose declarations were generated by LLM
  private _cachedFiles = new Set<string>(); // Stores full paths of files whose declarations were taken from cache

  constructor(llmProcessor: LLMProcessor, config: SviConfig) {
    this.llmProcessor = llmProcessor;
    this.config = config;
  }

  public async loadDependenciesDeclarations(sviFile: SVIFile): Promise<boolean> {
    logger.trace("Starting to load dependency declarations...");

    if (!sviFile.dependencies || sviFile.dependencies.length === 0) {
      logger.trace("No dependencies specified for this SVI file.");
      return true;
    }

    for (const dependency of sviFile.dependencies) {
      logger.trace(`Processing dependency: '${dependency}'`);

      let resolvedPath: string | null = null;
      const attemptedPaths: string[] = [];

      // 1. Try resolving relative to the sviFile's directory
      const relativePathAttempt = path.resolve(sviFile.getSviFileDirectory(), dependency);
      attemptedPaths.push(relativePathAttempt);
      if (fs.existsSync(relativePathAttempt)) {
        resolvedPath = relativePathAttempt;
      }

      // 2. If not found, iterate through searchPaths
      if (!resolvedPath) {
        for (const searchPath of this.config.searchPaths) {
          const searchPathAttempt = path.resolve(searchPath, dependency);
          attemptedPaths.push(searchPathAttempt);
          if (fs.existsSync(searchPathAttempt)) {
            resolvedPath = searchPathAttempt;
            break;
          }
        }
      }

      if (!resolvedPath) {
        // If file not found after all attempts
        const pathsTried = attemptedPaths.join("', '");
        logger.error(
          `File '${dependency}' from 'Dependencies' section not found. It was attempted to be found at: '${pathsTried}'`
        );
        return false;
      }
      logger.trace(`Resolved path for '${dependency}': '${resolvedPath}'`);

      const dependencyFileDirectory = path.dirname(resolvedPath);
      const cacheManager = new CacheManager(dependencyFileDirectory);
      let declarations: string | null = null;

      // 3. Check cache
      if (cacheManager.isFileExportsCacheValid(resolvedPath)) {
        declarations = cacheManager.getFileExportsFromCache(resolvedPath);
        if (declarations) {
          this._cachedFiles.add(resolvedPath);
          this._declarations.push({ originalDependencyName: dependency, fullPath: resolvedPath, content: declarations });
          logger.trace(`Declarations for '${dependency}' loaded from cache.`);
          continue; // Go to the next dependency
        }
      }

      // 4. Ask LLM if not cached or cache invalid/empty
      logger.info(`LLM will be called to generate declarations for file: '${dependency}'`);
      this._llmGeneratedFiles.add(resolvedPath);

      let fileContent: string;
      try {
        fileContent = fs.readFileSync(resolvedPath, "utf8");
      } catch (error) {
        logger.error(`Error reading dependency file '${resolvedPath}': ${error instanceof Error ? error.message : String(error)}`);
        return false;
      }

      const programmingLanguagePhrase = this.config.programmingLanguage
        ? `programming language ${this.config.programmingLanguage}`
        : "";

      const prompt = extractDeclarationsPromptTemplate
        .replace("{{programmingLanguage}}", programmingLanguagePhrase)
        .replace("{{sourceCode}}", fileContent);

      declarations = await this.llmProcessor.ask(prompt);

      if (!declarations) {
        logger.error(`LLM returned no result for declarations for file: '${dependency}'`);
        return false;
      }

      // 5. Update cache
      cacheManager.updateFileExportsInCache(resolvedPath, declarations);
      this._declarations.push({ originalDependencyName: dependency, fullPath: resolvedPath, content: declarations });
      logger.trace(`Declarations for '${dependency}' generated by LLM and cached.`);
    }

    logger.info("Dependencies declarations retrieved and added to the main prompt.");
    if (this._llmGeneratedFiles.size > 0) {
      logger.info(
        `Files generated by LLM: ${Array.from(this._llmGeneratedFiles)
          .map((p) => path.basename(p))
          .join(", ")}`
      );
    } else {
      logger.info("No files were generated by LLM for declarations.");
    }
    if (this._cachedFiles.size > 0) {
      logger.info(
        `Files taken from cache: ${Array.from(this._cachedFiles)
          .map((p) => path.basename(p))
          .join(", ")}`
      );
    } else {
      logger.info("No files were taken from cache for declarations.");
    }

    return true;
  }

  public getDependenciesDeclarationsAsString(): string {
    if (this._declarations.length === 0) {
      return "";
    }

    let result = "";
    for (let i = 0; i < this._declarations.length; i++) {
      const dep = this._declarations[i];
      result += `${dep.originalDependencyName} declarations\n\n`;
      result += `${dep.content}\n`;
      if (i < this._declarations.length - 1) {
        result += "\n"; // Add an empty line between declarations, but not after the last one
      }
    }
    return result;
  }
}