import fs from "fs";
import path from "path";

import { SVIFile } from "./types";
import { LLMProcessor } from "../llm/llm";
import { SviConfig } from "../config/config";
import { extractDeclarationsPromptTemplate } from "./prompts/extractDeclarations";
import CacheManager from "./cacheManager";
import logger from "../utils/logger";
import { getRelativePath } from "../utils/file";

export default class SviDependencies {
  private llmProcessor: LLMProcessor;
  private config: SviConfig;
  private dependenciesDeclarations: string = "";
  private llmGeneratedFiles: string[] = [];
  private cachedFiles: string[] = [];

  constructor(llmProcessor: LLMProcessor, config: SviConfig) {
    this.llmProcessor = llmProcessor;
    this.config = config;
  }

  /**
   * Loads declarations for all dependencies specified in the SVI file.
   * Declarations are either retrieved from cache or generated by LLM.
   * @param sviFile The SVIFile instance containing dependency information.
   * @returns True if all declarations were successfully loaded, false otherwise.
   */
  public async loadDependenciesDeclarations(sviFile: SVIFile): Promise<boolean> {
    this.dependenciesDeclarations = ""; // Reset declarations for a new load operation
    this.llmGeneratedFiles = [];
    this.cachedFiles = [];

    if (!sviFile.dependencies || sviFile.dependencies.length === 0) {
      logger.trace("No dependencies found for this SVI file.");
      return true;
    }

    const collectedDeclarations: { relativePath: string; declaration: string }[] = [];

    for (const dependencyFilename of sviFile.dependencies) {
      logger.trace(`Processing dependency: ${dependencyFilename}`);

      const sviFileDirectory = sviFile.getSviFileDirectory();
      const dependencyFullPath = path.resolve(sviFileDirectory, dependencyFilename);
      const relativeDependencyPath = getRelativePath(dependencyFullPath, this.config.configDir);

      if (!fs.existsSync(dependencyFullPath)) {
        logger.error(`File '${dependencyFilename}' from 'Dependencies' section not found at path '${dependencyFullPath}'.`);
        this.dependenciesDeclarations = ""; // Clear any partial declarations on error
        return false;
      }

      const cacheManager = new CacheManager(path.dirname(dependencyFullPath));
      let currentDeclaration: string | null = null;

      logger.trace(`Checking cache for ${relativeDependencyPath}`);
      if (cacheManager.isFileExportsCacheValid(dependencyFullPath)) {
        const cachedExports = cacheManager.getFileExportsFromCache(dependencyFullPath);
        if (cachedExports) {
          currentDeclaration = cachedExports;
          this.cachedFiles.push(relativeDependencyPath);
          logger.trace(`Cache hit for ${relativeDependencyPath}. Using cached declarations.`);
        } else {
          // Cache was considered valid, but getFileExportsFromCache returned null.
          // This could indicate a corrupted cache entry or an empty file exports cache.
          // Proceed to generate with LLM.
          logger.trace(`Cache valid but getFileExportsFromCache returned null for ${relativeDependencyPath}. Will generate with LLM.`);
        }
      } else {
        logger.trace(`Cache invalid for ${relativeDependencyPath}. Will generate with LLM.`);
      }

      if (!currentDeclaration) { // If declarations were not retrieved from cache
        logger.info(`LLM will be called to generate declarations for file: '${relativeDependencyPath}'.`);
        this.llmGeneratedFiles.push(relativeDependencyPath); // Add to list of LLM-generated files

        let fileContent: string;
        try {
          fileContent = fs.readFileSync(dependencyFullPath, 'utf-8');
        } catch (readError: any) {
          logger.error(`Failed to read dependency file '${relativeDependencyPath}': ${readError.message}`);
          this.dependenciesDeclarations = "";
          return false;
        }

        const programmingLanguagePhrase = this.config.programmingLanguage ? `programming language ${this.config.programmingLanguage}` : '';
        const prompt = extractDeclarationsPromptTemplate
          .replace('{{programmingLanguage}}', programmingLanguagePhrase)
          .replace('{{sourceCode}}', fileContent);

        const promptDescription = `Declarations extraction from '${relativeDependencyPath}'`;

        const llmResult = await this.llmProcessor.ask(prompt, undefined, promptDescription);

        if (!llmResult) {
          logger.error(`LLM returned no result for declarations extraction from '${relativeDependencyPath}'.`);
          this.dependenciesDeclarations = "";
          return false;
        }

        currentDeclaration = llmResult;
        // Update cache only if LLM successfully returned a result
        cacheManager.updateFileExportsInCache(dependencyFullPath, llmResult);
        logger.trace(`Cache updated for ${relativeDependencyPath}.`);
      }

      if (currentDeclaration) {
        collectedDeclarations.push({ relativePath: relativeDependencyPath, declaration: currentDeclaration });
      } else {
        // This case should ideally not be reached if all preceding logic is sound.
        // It indicates a failure to get declarations from both cache and LLM.
        logger.error(`Failed to retrieve or generate declarations for '${relativeDependencyPath}' after all attempts.`);
        this.dependenciesDeclarations = "";
        return false;
      }
    }

    // Format all collected declarations into the final string
    this.dependenciesDeclarations = collectedDeclarations.map(item =>
      `Declarations from file: ${item.relativePath}\n\n${item.declaration}`
    ).join('\n\n'); // Joins with two newlines to create an empty line between blocks

    logger.info("Dependencies declarations were retrieved and added to the main prompt.");
    logger.info(`Files processed by LLM: ${this.llmGeneratedFiles.join(', ') || 'None'}`);
    logger.info(`Files taken from cache: ${this.cachedFiles.join(', ') || 'None'}`);

    return true;
  }

  /**
   * Returns the accumulated dependencies declarations as a single string.
   * This string is formatted according to the specified requirements.
   * @returns The formatted string of all dependency declarations.
   */
  public getDependenciesDeclarationsAsString(): string {
    return this.dependenciesDeclarations;
  }
}